# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduled_post_report',
            name='user_account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='management.user_account'),
            preserve_default=False,
        ),
    ]
