# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-07 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_scheduled_post_report_user_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduled_post',
            name='post_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
